### ISSUE TITLE
Recognize keyword "partner"

### ISSUE THREAD

**Issue by NatoBoram** [deitry/apt-source-list-syntax#3]
![code](https://user-images.githubusercontent.com/10495562/97022721-74f1b100-1522-11eb-9104-d150c9911e10.png)

**Comment by deitry** [comment]
Hi!
I added `partner` keyword in the last update, though as far as I understand from [man page](https://manpages.debian.org/jessie/apt/sources.list.5.en.html) in general case suite can be any word that exists in the given repo. I don't know what's the best way to solve it.
